Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu'
  config.vm.box_url = 'https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vbox.box'
  config.vm.host_name = 'ubuntu'
  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--memory', 1024 * 3]
  end
  config.vm.network :private_network, ip: '172.17.8.100'
end
